name: tests
on: [ push, pull_request ]

jobs:
  tests_nightly:
    name: tests, fmt & clippy @nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - name: doc tests
        run: cargo test --doc
      - name: tests - no default features
        run: cargo test --no-default-features --tests
      - name: tests - std
        run: cargo test --no-default-features --features std --tests
      - name: tests - error_trait
        run: cargo test --no-default-features --features error_trait --tests
      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets -- --deny warnings
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
  tests_1_77:
    name: tests, fmt & clippy @ 1.77.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.77.0
          components: rustfmt, clippy
      - name: doc tests
        run: cargo test --doc
      - name: tests - no default features
        run: cargo test --no-default-features --tests
      - name: tests - std
        run: cargo test --features std --tests
      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets -- --deny warnings
  semver-check:
    name: semver check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
  kani-compile-check:
    name: Kani compile check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: model-checking/kani-github-action@v1.0
        with:
          kani-version: latest
          args: --all-features --only-codegen