name: tests
on: [push, pull_request]

jobs:
  tests_fmt_clippy:
    name: tests, fmt & clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - name: doc tests
        run: cargo test --doc
      - name: tests
        run: cargo test --tests
      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy -- --deny warnings
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2